kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8082
name = "API Server"
paths = ["/api", "/ebdaa-dashboard/", "/ebdaa-docs/", "/ebdaa-docs", "/ebdaa-skill-matrix-template.xlsx", "/ebdaa-spreadsheet/", "/ebdaa-spreadsheet"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/api-server", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

[services.production.run.env]
PORT = "8082"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
