import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import ExcelJS from "exceljs";

interface ExportData {
  title: string;
  filename: string;
  headers: string[];
  rows: (string | number)[][];
  subtitle?: string;
}

export const exportToPDF = ({ title, filename, headers, rows, subtitle }: ExportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Branding Header
  doc.setFontSize(18);
  doc.setTextColor(10, 10, 10);
  doc.text(title, 14, 20);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, 14, 28);
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by HRM Development System | ${new Date().toLocaleString()}`, 14, 34);

  autoTable(doc, {
    startY: 40,
    head: [headers],
    body: rows,
    theme: "striped",
    headStyles: { fillColor: [10, 10, 10], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { top: 40 },
  });

  doc.save(`${filename}.pdf`);
};

export const exportToExcel = async ({ title, filename, headers, rows }: ExportData) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Data");

  // Title Row
  const titleRow = worksheet.addRow([title]);
  titleRow.font = { bold: true, size: 14 };
  worksheet.mergeCells(1, 1, 1, headers.length);

  // Subtitle / Branding
  const brandRow = worksheet.addRow([`Generated by HRM Development System | ${new Date().toLocaleString()}`]);
  brandRow.font = { italic: true, size: 10, color: { argb: "FF666666" } };
  worksheet.mergeCells(2, 1, 2, headers.length);

  worksheet.addRow([]); // Spacer

  // Header Row
  const headerRow = worksheet.addRow(headers);
  headerRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF0A0A0A" },
    };
    cell.font = { color: { argb: "FFFFFFFF" }, bold: true };
  });

  // Data Rows
  rows.forEach((rowData) => {
    worksheet.addRow(rowData);
  });

  // Auto-fit columns
  worksheet.columns.forEach((column) => {
    let maxLength = 0;
    column.eachCell!({ includeEmpty: true }, (cell) => {
      const columnLength = cell.value ? cell.value.toString().length : 10;
      if (columnLength > maxLength) {
        maxLength = columnLength;
      }
    });
    column.width = maxLength < 12 ? 12 : maxLength + 2;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.xlsx`;
  link.click();
};
