import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import ExcelJS from "exceljs";
import { TAJAWAL_FONT_BASE64 } from "@/shared/lib/fonts";
import { reshape } from "arabic-reshaper";

interface ExportData {
  title: string;
  filename: string;
  headers: string[];
  rows: (string | number)[][];
  subtitle?: string;
}

const fixArabic = (text: string) => {
  if (!text) return "";
  // Check if text contains Arabic characters
  const isArabic = /[\u0600-\u06FF]/.test(text);
  if (!isArabic) return text;

  // Reshape Arabic characters to their connected forms
  const reshaped = reshape(text);
  // Reverse the string for LTR rendering engines like jsPDF
  return reshaped.split("").reverse().join("");
};

export const exportToPDF = ({ title, filename, headers, rows, subtitle }: ExportData) => {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  // Add and set Arabic font
  doc.addFileToVFS("Tajawal.ttf", TAJAWAL_FONT_BASE64);
  doc.addFont("Tajawal.ttf", "Tajawal", "normal");
  doc.setFont("Tajawal");

  const pageWidth = doc.internal.pageSize.getWidth();

  // Branding Header
  doc.setFontSize(18);
  doc.setTextColor(10, 10, 10);
  doc.text(fixArabic(title), pageWidth - 14, 20, { align: "right" });

  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(fixArabic(subtitle), pageWidth - 14, 28, { align: "right" });
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = `Generated by HRM Development System | ${new Date().toLocaleString()}`;
  doc.text(fixArabic(footerText), pageWidth - 14, 34, { align: "right" });

  autoTable(doc, {
    startY: 40,
    head: [headers.map(fixArabic)],
    body: rows.map(row => row.map(cell => fixArabic(String(cell)))),
    theme: "striped",
    styles: { 
      font: "Tajawal", 
      halign: "right",
    },
    headStyles: { 
      fillColor: [10, 10, 10], 
      textColor: [255, 255, 255],
      font: "Tajawal",
    },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { top: 40 },
  });

  doc.save(`${filename}.pdf`);
};

export const exportToExcel = async ({ title, filename, headers, rows }: ExportData) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Data");

  // Title Row
  const titleRow = worksheet.addRow([title]);
  titleRow.font = { bold: true, size: 14 };
  worksheet.mergeCells(1, 1, 1, headers.length);

  // Subtitle / Branding
  const brandRow = worksheet.addRow([`Generated by HRM Development System | ${new Date().toLocaleString()}`]);
  brandRow.font = { italic: true, size: 10, color: { argb: "FF666666" } };
  worksheet.mergeCells(2, 1, 2, headers.length);

  worksheet.addRow([]); // Spacer

  // Header Row
  const headerRow = worksheet.addRow(headers);
  headerRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF0A0A0A" },
    };
    cell.font = { color: { argb: "FFFFFFFF" }, bold: true };
  });

  // Data Rows
  rows.forEach((rowData) => {
    worksheet.addRow(rowData);
  });

  // Auto-fit columns
  worksheet.columns.forEach((column) => {
    let maxLength = 0;
    column.eachCell!({ includeEmpty: true }, (cell) => {
      const columnLength = cell.value ? cell.value.toString().length : 10;
      if (columnLength > maxLength) {
        maxLength = columnLength;
      }
    });
    column.width = maxLength < 12 ? 12 : maxLength + 2;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.xlsx`;
  link.click();
};
